### PR TITLE
Decoupling sort and time offsets

### PR DESCRIPTION
**Pull request by teddywilson**
- Also made views in the grid views text views

### CODE REVIEW

**Comment by bret-fears** [comment]
https://circleci.com/gh/willowtreeapps/spruce-android/300 apparently CI has issues with the @FloatRange annotation

**Comment by teddywilson** [comment]
@bret-fears anything I can do to fix that?

**Comment by bret-fears** [comment]
Looks like an issue with the CardLayout on`spruce-android/app/src/main/java/com/willowtreeapps/spurceexampleapp/fragments/ViewFragment.java:70: error: cannot find symbol
            childView.setText(""+i);`

**Comment by teddywilson** [comment]
Should be resolved now. I must have messed something up when I merged

**Comment by bret-fears** [comment]
Yep, that did it

**Pull request merged**
